import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src="/images/backdrop.svg"
        width={500}
        height={300}
        className="w-full fixed top-0 right-0 pointer-events-none -z-10"
      />
    </>
  );
}
